export async function GET() {
  const xsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | Quantyro Technologies</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; color: #1e293b; background: #f8fafc; margin: 0; padding: 40px 20px; }
          .container { max-width: 1080px; margin: 0 auto; background: #fff; padding: 36px; border-radius: 16px; box-shadow: 0 10px 25px -5px rgb(0 0 0 / 0.05); border: 1px solid #e2e8f0; }
          h1 { font-size: 26px; font-weight: 800; color: #0f172a; margin-top: 0; margin-bottom: 8px; letter-spacing: -0.02em; }
          p { color: #64748b; font-size: 14.5px; margin-bottom: 24px; line-height: 1.5; }
          table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13.5px; }
          th { background: #f8fafc; text-align: left; padding: 12px 16px; font-weight: 700; color: #0f172a; border-bottom: 2px solid #e2e8f0; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; }
          td { padding: 13px 16px; border-bottom: 1px solid #f1f5f9; word-break: break-all; }
          tr:hover td { background: #f8fafc; }
          a { color: #1768d6; text-decoration: none; font-weight: 600; }
          a:hover { text-decoration: underline; color: #0c4a9e; }
          .badge { display: inline-block; padding: 3px 9px; border-radius: 6px; background: #eff6ff; color: #1768d6; font-size: 11.5px; font-weight: 700; font-family: monospace; border: 1px solid #dbeafe; }
          .subhead { font-size: 13px; color: #94a3b8; margin-top: 30px; text-align: right; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>XML Sitemap Index</h1>
          <p>This is a structured XML Sitemap generated by <strong>Quantyro Technologies</strong> for search engines and crawlers (Google, Bing, Perplexity, OpenAI).</p>
          
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <table>
              <thead>
                <tr>
                  <th width="70%">Sitemap Section</th>
                  <th width="30%">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td style="color: #64748b; font-family: monospace; font-size: 12.5px;">
                      <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),' +00:00')"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <table>
              <thead>
                <tr>
                  <th width="65%">Page URL</th>
                  <th width="15%">Priority</th>
                  <th width="20%">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td>
                      <span class="badge"><xsl:value-of select="sitemap:priority"/></span>
                    </td>
                    <td style="color: #64748b; font-family: monospace; font-size: 12px;">
                      <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          <div class="subhead">Quantyro Technologies XML Sitemap Engine</div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

  return new Response(xsl, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
